server:
  port: 8082

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/nim?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#  redis:
#    cluster:
#      nodes: "127.0.0.1:6371,127.0.0.2:6371,127.0.0.1:6373"
#    #    host: 127.0.0.1
#    #    port: 6379
#    timeout: 3000
#    redisson:
#      config: classpath:redisson_cluster.yml
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.server.entity

#showSql
logging:
  level:
    com:
      example:
        mapper: debug

