server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/nim?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      # 消息发送失败返回到队列中, yml需要配置 publisher-returns: true
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual #手动ACK
        default-requeue-rejected: false #个字段一定要设置成 false 不然无法消费的数据不会进入死信队列的
        concurrency: 1 #同一个队列启动几个消费者
        max-concurrency: 1 #启动消费者最大数量
        prefetch: 1 #限制每次发送一条数据
        retry:
          enabled: true #是否支持重试

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.server.entity

#showSql
logging:
  level:
    com:
      example:
        mapper: debug

